// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf7KuBJxfqBEH8yLmsHURKXXXnKwZ4DzI',
    appId: '1:574703750772:web:25a6ec757bd5b428da4b21',
    messagingSenderId: '574703750772',
    projectId: 'authentication-bf431',
    authDomain: 'authentication-bf431.firebaseapp.com',
    storageBucket: 'authentication-bf431.firebasestorage.app',
    databaseURL:
        "https://authentication-bf431-default-rtdb.asia-southeast1.firebasedatabase.app",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqQRN6DzkCxRL1HFpRkqmean8bZvKeekw',
    appId: '1:574703750772:android:39a168c041d639e3da4b21',
    messagingSenderId: '574703750772',
    projectId: 'authentication-bf431',
    storageBucket: 'authentication-bf431.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIwPerDHSgVV5vQ3SEGSo_3jZb-HRJxa0',
    appId: '1:574703750772:ios:4dd0b7197193273fda4b21',
    messagingSenderId: '574703750772',
    projectId: 'authentication-bf431',
    storageBucket: 'authentication-bf431.firebasestorage.app',
    iosBundleId: 'com.example.authenticationfire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIwPerDHSgVV5vQ3SEGSo_3jZb-HRJxa0',
    appId: '1:574703750772:ios:4dd0b7197193273fda4b21',
    messagingSenderId: '574703750772',
    projectId: 'authentication-bf431',
    storageBucket: 'authentication-bf431.firebasestorage.app',
    iosBundleId: 'com.example.authenticationfire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDf7KuBJxfqBEH8yLmsHURKXXXnKwZ4DzI',
    appId: '1:574703750772:web:f445b0193c5da510da4b21',
    messagingSenderId: '574703750772',
    projectId: 'authentication-bf431',
    authDomain: 'authentication-bf431.firebaseapp.com',
    storageBucket: 'authentication-bf431.firebasestorage.app',
  );
}
